site_name: Development Kit
site_url: https://devkit.techcyte.com

repo_name: techcyte/devkit
repo_url: https://github.com/techcyte/devkit

theme:
  name: material
  palette:
    primary: '#25216C'
    accent: '#3563ED'
  features:
    - content.code.copy
    - search.suggest
    - content.tabs.link
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.tabs.link
  logo: img/logo-techcyte-white.svg
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  toc:
    permalink: true
    slugify: !!python/name:pymdownx.slugs.uslugify
    toc_depth: 3

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - tables

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - minify
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: numpy
  - mkdocs-jupyter:
      include_source: True
      execute: false
      ignore_h1_titles: True
      show_input: True
      theme: light
      kernel_name: python3
      allow_errors: false
      include_requirejs: true
      no_input: false

nav:
  - Home: index.md
  - API Bridge: api-bridge.md
  - Model Hosting Service: model-hosting-service.md
  - Guides:
    - Intro: guides/index.md
    - Techcyte App:
      - Bulk Scan Import Tool: guides/bulk-import-tool/index.md
      - Creating a case: guides/creating-a-case/index.md
      - Creating a debug request: guides/creating-a-debug-request/index.md
      - Creating an AI request type: guides/creating-an-ai-request-type/index.md
      - Creating an API key: guides/creating-an-api-key/index.md
      - Model Hosting Service: guides/model-hosting-service/index.md
      - Posting External Model Results: guides/posting-external-model-results/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/techcyte/devkit
